details:
  page_title: Streamboard
  color_mode: black
layout:
  - row:

      - col:
          - tile_template: stream
            tile_id: stream_ex


      - col:
          - tile_template: stream
            tile_id: stream_ex

  - row:
      - col:
          - tile_template: just_value
            tile_id: jv_ex
            title: Just value

      - col flip-time-60:
          - tile_template: big_value
            tile_id: bv_ex
            title: Big value
            value:
              - big_value: 52

          - tile_template: custom
            tile_id: custom_ex
            title: Custom

      - col flip-time-60:
          - tile_template: text
            tile_id: txt_ex
            title: text

          - tile_template: simple_percentage
            tile_id: sp_ex
            title: Percentage

